# Generated by Django 5.2.17 on 2026-09-06 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_genres', models.JSONField(default=list)),
                ('preferred_eras', models.JSONField(default=list)),
                ('default_mood', models.CharField(blank=True, default='', max_length=50)),
                ('discovery_style', models.CharField(choices=[('familiar', 'Familiar'), ('balanced', 'Balanced'), ('new', 'New')], default='balanced', max_length=20)),
                ('recommendation_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('on_demand', 'On demand')], default='on_demand', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
