# Generated by Django 5.2.17 on 2026-09-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_spotifyconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyconnection',
            name='spotify_display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
