# Generated by Django 5.2.17 on 2026-09-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_spotifyconnection_spotify_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyconnection',
            name='spotify_account_id',
            field=models.CharField(max_length=255),
        ),
    ]
