# Generated by Django 5.2.17 on 2026-09-06 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('era', models.CharField(blank=True, max_length=50)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('discovery_style', models.CharField(choices=[('familiar', 'Familiar'), ('balanced', 'Balanced'), ('new', 'New')], default='balanced', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
